### ISSUE TITLE
Adding JSONP to Overcome Same-Origin Policy Issues

### ISSUE THREAD

**Issue by wiiman96** [minecraftforum/widget#25]
```javascript
		var xmlhttp = new XMLHttpRequest();
		var url = 'http://widget.mcf.li/mc-mods/minecraft/cofhcore.json'; //substitute for any mod/pack
		xmlhttp.onreadystatechange = function() {
			if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
				var parseResult = JSON.parse(xmlhttp.responseText);
			}
		}
		xmlhttp.open("GET", url, true);
		xmlhttp.send();
```
This returns: 
`XMLHttpRequest cannot load http://widget.mcf.li/mc-mods/minecraft/cofhcore.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://site-name-here.site' is therefore not allowed access.`

JSONP allows for a workaround by taking advantage of `<script>`'s external capabilities.

By wrapping the JSON data within a function, you allow sites on other domains to reference the JSONP script's contents using `<script src="[path to JSONP]">`. This is because Same-Origin Policy does not take effect on HTML script tags.

**Comment by citricsquid** [comment]
I have enabled the access control headers that should allow you to make requests without requiring JSONP. Sorry for the long turnaround on this!
